/*
 * Copyright 2026 Dmitry Nekrasov and utf8-string library contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the LICENSE file.
 */

package utf8string.generator

// A string constant must fit the 65,535 bytes of modified UTF-8 that the JVM gives a constant; longer data is split.
private const val MAX_CONSTANT_BYTES = 65_535
private const val MAX_CHUNK_CHARS = 60_000
private const val MAX_LINE_CHARS = 100

// A generated Kotlin file in package utf8string. Every char outside printable ASCII is escaped.
class KotlinFile(sources: List<String>) {
    private val text = StringBuilder()

    init {
        text.appendLine("/*")
        text.appendLine(" * Copyright 2026 Dmitry Nekrasov and utf8-string library contributors.")
        text.appendLine(" * Use of this source code is governed by the Apache 2.0 license that can be found in the LICENSE file.")
        text.appendLine(" */")
        text.appendLine()
        text.appendLine("// Generated by utf8-string-generator, do not edit. The data is derived from")
        for (source in sources) text.appendLine("// $source,")
        text.appendLine("// Copyright (c) 1991-2026 Unicode, Inc., under the Unicode License V3 in unicode/license.txt.")
        text.appendLine()
        text.appendLine("package utf8string")
    }

    fun intConstant(comment: String, name: String, value: Int) {
        comment(comment)
        text.appendLine("internal const val $name: Int = $value")
    }

    // With lines, value is text whose lines each get a line of source; otherwise the source is split anywhere.
    fun stringConstant(comment: String, name: String, value: String, visibility: String = "internal", lines: Boolean = false) {
        comment(comment)
        check(modifiedUtf8Length(value) <= MAX_CONSTANT_BYTES) { "$name is too long for one constant" }
        val declaration = "$visibility const val $name: String ="
        if (!lines && escape(value).length <= MAX_LINE_CHARS) {
            text.appendLine("$declaration \"${escape(value)}\"")
            return
        }
        text.appendLine(declaration)
        val sourceLines = if (lines) {
            check(value.endsWith('\n')) { "$name does not end with a line break" }
            value.split('\n').dropLast(1).map { escape(it) + "\\n" }
        } else {
            escape(value).chunkedEscapes()
        }
        sourceLines.forEachIndexed { i, line ->
            text.append("    \"").append(line).append('"').appendLine(if (i < sourceLines.size - 1) " +" else "")
        }
    }

    // Lines of text, as one constant or, above the constant size, as a list of constants.
    fun linesConstant(comment: String, name: String, lines: List<String>) {
        val chunks = ArrayList<List<String>>()
        var chunk = ArrayList<String>()
        var chars = 0
        for (line in lines) {
            if (chars + line.length + 1 > MAX_CHUNK_CHARS) {
                chunks += chunk
                chunk = ArrayList()
                chars = 0
            }
            chunk += line
            chars += line.length + 1
        }
        chunks += chunk
        comment(comment)
        text.appendLine("internal val $name: List<String> = listOf(${chunks.indices.joinToString { "${name}_$it" }})")
        chunks.forEachIndexed { i, chunkLines ->
            stringConstant("", "${name}_$i", chunkLines.joinToString("") { it + "\n" }, visibility = "private", lines = true)
        }
    }

    private fun comment(comment: String) {
        text.appendLine()
        if (comment.isNotEmpty()) wrap(comment, 117).forEach { text.appendLine("// $it") }
    }

    override fun toString(): String = text.toString()
}

private fun escape(value: String): String = buildString {
    for (char in value) {
        if (char in ' '..'~' && char != '"' && char != '\\' && char != '$') append(char) else append("\\u%04X".format(char.code))
    }
}

// Splits escaped text into source lines without cutting an escape.
private fun String.chunkedEscapes(): List<String> {
    val lines = ArrayList<String>()
    var start = 0
    while (start < length) {
        var end = minOf(start + MAX_LINE_CHARS, length)
        val escapeStart = lastIndexOf("\\u", end - 1)
        if (escapeStart in start..<end && escapeStart + 6 > end) end = escapeStart
        lines += substring(start, end)
        start = end
    }
    return lines
}

private fun modifiedUtf8Length(value: String): Int = value.sumOf { char ->
    when (char.code) {
        in 0x01..0x7F -> 1
        in 0x80..0x7FF, 0 -> 2
        else -> 3
    }
}

private fun wrap(text: String, width: Int): List<String> {
    val lines = ArrayList<String>()
    var line = StringBuilder()
    for (word in text.split(' ')) {
        if (line.isNotEmpty() && line.length + 1 + word.length > width) {
            lines += line.toString()
            line = StringBuilder()
        }
        if (line.isNotEmpty()) line.append(' ')
        line.append(word)
    }
    lines += line.toString()
    return lines
}
